### ISSUE TITLE
Expo client crash on iOS when asking Permissions again.

### ISSUE THREAD

**Issue by giautm** [expo/expo-permissions#1]
Expo crashing with following error in Console. I think that releated to expo-permissions module (or not). I'm using Expo SDKv29, Expo client version is 2.8.2.

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM isEqualToString:]: unrecognized selector sent to instance 0x2809d1050'
*** First throw call stack:
(0x18ff3bef8 0x18f109a40 0x18fe53154 0x18ff41810 0x18ff434bc 0x100bf43d4 0x100bf3714 0x18ff43660 0x18fe1f980 0x100be0354 0x18f9736c8 0x18f974484 0x18f9209ec 0x18feca1bc 0x18fec5084 0x18fec45b8 0x192138584 0x1bc7bb558 0x100bcfa54 0x18f984b94)
```

Both `askAsync` & `getAsync` cause a crash:
```js
await Permissions.askAsync(Permissions.LOCATION)
```

*Noted: I'm trying reproduced this case on snack but It's not happened.*
https://snack.expo.io/@giautm/test-permissions-crash

**Comment by bbarthec** [comment]
@giautm, why did you close the issue? Is the problem resolved? If so, how?

**Comment by giautm** [comment]
@bbarthec : Sadly, I found a crash with other permissions. No idea why it happened, so I reopen the issues.
```
  const { status } = await Permissions.askAsync(Permissions.SMS)
```

**Comment by giautm** [comment]
[Update]: After I upgraded to SDKv30, the issue was gone.

**Comment by sjchmiela** [comment]
Happy to hear that! I'll close this issue tentatively, feel free to reopen it if you encounter any problems! 🙂
